### ISSUE TITLE
%matplotlib widget not working

### ISSUE THREAD

**Issue by doofkatze** [matplotlib/ipympl#132]
I've followed the installation instruction and consulted previous posts. But `%matplotlib widget` still give me error messages. 

`%matplotlib widget`

`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-7b899824b39e> in <module>
----> 1 get_ipython().run_line_magic('matplotlib', 'widget')

~/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2305                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2306             with self.builtin_trap:
-> 2307                 result = fn(*args, **kwargs)
   2308             return result
   2309 

</home/gin/.local/lib/python3.6/site-packages/decorator.py:decorator-gen-108> in matplotlib(self, line)

~/.local/lib/python3.6/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

~/.local/lib/python3.6/site-packages/IPython/core/magics/pylab.py in matplotlib(self, line)
     97             print("Available matplotlib backends: %s" % backends_list)
     98         else:
---> 99             gui, backend = self.shell.enable_matplotlib(args.gui)
    100             self._show_matplotlib_backend(args.gui, backend)
    101 

~/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py in enable_matplotlib(self, gui)
   3382                 gui, backend = pt.find_gui_and_backend(self.pylab_gui_select)
   3383 
-> 3384         pt.activate_matplotlib(backend)
   3385         pt.configure_inline_support(self, backend)
   3386 

~/.local/lib/python3.6/site-packages/IPython/core/pylabtools.py in activate_matplotlib(backend)
    311     matplotlib.rcParams['backend'] = backend
    312 
--> 313     import matplotlib.pyplot
    314     matplotlib.pyplot.switch_backend(backend)
    315 

/usr/local/lib/python3.6/dist-packages/matplotlib-3.1.0+860.g4edadf965-py3.6-linux-x86_64.egg/matplotlib/pyplot.py in <module>
     38 from matplotlib import docstring
     39 from matplotlib.backend_bases import FigureCanvasBase
---> 40 from matplotlib.figure import Figure, figaspect
     41 from matplotlib.gridspec import GridSpec
     42 from matplotlib import rcParams, rcParamsDefault, get_backend, rcParamsOrig

/usr/local/lib/python3.6/dist-packages/matplotlib-3.1.0+860.g4edadf965-py3.6-linux-x86_64.egg/matplotlib/figure.py in <module>
     18 
     19 from matplotlib import rcParams
---> 20 from matplotlib import backends, docstring, projections
     21 from matplotlib import __version__ as _mpl_version
     22 from matplotlib import get_backend

/usr/local/lib/python3.6/dist-packages/matplotlib-3.1.0+860.g4edadf965-py3.6-linux-x86_64.egg/matplotlib/projections/__init__.py in <module>
      2 from .geo import AitoffAxes, HammerAxes, LambertAxes, MollweideAxes
      3 from .polar import PolarAxes
----> 4 from mpl_toolkits.mplot3d import Axes3D
      5 
      6 

/usr/lib/python3/dist-packages/mpl_toolkits/mplot3d/__init__.py in <module>
      4 import six
      5 
----> 6 from .axes3d import Axes3D

/usr/lib/python3/dist-packages/mpl_toolkits/mplot3d/axes3d.py in <module>
     30 import matplotlib.transforms as mtransforms
     31 from matplotlib.axes import Axes, rcParams
---> 32 from matplotlib.cbook import _backports
     33 from matplotlib.colors import Normalize, LightSource
     34 from matplotlib.transforms import Bbox

ImportError: cannot import name '_backports' `

**Comment by toufaluancaocao** [comment]
even `import ipympl` gives error although I've installed it

`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-1963c569fb20> in <module>
----> 1 import ipympl

ModuleNotFoundError: No module named 'ipympl'`

**Comment by thomasaarholt** [comment]
Sounds like you are having trouble with your python installation / virtual environment?

Try `which python` and `which jupyter` and see if they coincide with where you have installed ipympl.

**Comment by vjmayr** [comment]
just because I forgot: you did  - pip install ipympl - ?

**Comment by JimmyPark001** [comment]
In the interactive window,  i can only  see  text/pain  and  text/html  .  I think i can figure out this issue if i can change MIME type into Image/png.   do you know how i can add that MIME type in VSC?

**Comment by himanshuGoyal52** [comment]
same issue ... if you found the result please tell crow

**Comment by thomasaarholt** [comment]
Folks, you're commenting on a 4 year old issue. While open, it's likely that your issue is not the same as the original OPs. 
Please include a reproducible example, or at least explain what you're doing to produce the error.

The following plot works fine on a new python 3.12 virtual environment. On my mac, I have done:

```bash
# created a fresh python environment inside the folder we're in
python -m venv .venv

# activated the python environment
source .venv/bin/activate

# installed the packages we need
pip install notebook ipympl matplotlib

# started jupyter notebook
jupyter notebook
```python
%matplotlib widget

import matplotlib.pyplot as plt

plt.figure()
plt.plot([1,2,3])
```

<img width="770" alt="image" src="https://github.com/matplotlib/ipympl/assets/2721423/67bf75a5-4f50-449d-a69d-24918c633dbc">

**Comment by martinRenou** [comment]
I'd even suggest opening a new issue with all the needed information for debugging your use case. 

Closing this one for triaging. Please stop commenting here 😁
